best_5p_fields = {'Add_lay_back', 'Add_lay_front',
                  'Backcontact_deposition_procedure',
                  'Backcontact_stack_sequence', 'Cell_architecture',
                  'Cell_area_measured', 'Cell_flexible',
                  'Cell_number_of_cells_per_substrate', 'Cell_semitransparent',
                  'Cell_semitransparent_wavelength_range',
                  'Cell_stack_sequence', 'EQE_measured',
                  'ETL_deposition_procedure', 'ETL_stack_sequence',
                  'Encapsulation', 'HTL_stack_sequence',
                  'JV_average_over_n_number_of_cells', 'JV_certified_values',
                  'JV_default_Jsc', 'JV_default_Jsc_scan_direction',
                  'JV_default_PCE', 'JV_default_PCE_scan_direction',
                  'JV_light_intensity', 'JV_light_masked_cell',
                  'JV_light_wavelength_range', 'JV_measured',
                  'JV_reverse_scan_PCE', 'Module',
                  'Module_JV_data_recalculated_per_cell',
                  'Module_number_of_cells_in_module',
                  'Outdoor_PCE_burn_in_observed',
                  'Outdoor_average_over_n_number_of_cells',
                  'Outdoor_detaild_weather_data_available',
                  'Outdoor_installation_number_of_solar_tracking_axis',
                  'Outdoor_irradiance_measured',
                  'Outdoor_location_coordinates',
                  'Outdoor_periodic_JV_measurements',
                  'Outdoor_potential_bias_range',
                  'Outdoor_spectral_data_available',
                  'Outdoor_temperature_range', 'Outdoor_tested',
                  'Outdoor_time_end', 'Outdoor_time_start',
                  'Perovskite_band_gap_graded',
                  'Perovskite_composition_a_ions',
                  'Perovskite_composition_a_ions_coefficients',
                  'Perovskite_composition_b_ions',
                  'Perovskite_composition_b_ions_coefficients',
                  'Perovskite_composition_c_ions',
                  'Perovskite_composition_c_ions_coefficients',
                  'Perovskite_composition_inorganic',
                  'Perovskite_composition_leadfree',
                  'Perovskite_composition_long_form',
                  'Perovskite_composition_perovskite_ABC3_structure',
                  'Perovskite_composition_perovskite_inspired_structure',
                  'Perovskite_composition_short_form',
                  'Perovskite_deposition_aggregation_state_of_reactants',
                  'Perovskite_deposition_number_of_deposition_steps',
                  'Perovskite_deposition_procedure',
                  'Perovskite_deposition_quenching_induced_crystallisation',
                  'Perovskite_deposition_solvent_annealing',
                  'Perovskite_deposition_solvents', 'Perovskite_dimension_0D',
                  'Perovskite_dimension_2D',
                  'Perovskite_dimension_2D3D_mixture',
                  'Perovskite_dimension_3D',
                  'Perovskite_dimension_3D_with_2D_capping_layer',
                  'Perovskite_dimension_list_of_layers',
                  'Perovskite_single_crystal', 'Ref_DOI_number', 'Ref_ID',
                  'Ref_ID_temp', 'Ref_data_entered_by_author', 'Ref_journal',
                  'Ref_lead_author', 'Ref_name_of_person_entering_the_data',
                  'Ref_original_filename_data_upload',
                  'Ref_part_of_initial_dataset', 'Ref_publication_date',
                  'Stabilised_performance_measured',
                  'Stability_PCE_burn_in_observed',
                  'Stability_average_over_n_number_of_cells',
                  'Stability_flexible_cell_number_of_bending_cycles',
                  'Stability_light_UV_filter',
                  'Stability_light_wavelength_range', 'Stability_measured',
                  'Stability_periodic_JV_measurements',
                  'Stability_potential_bias_range',
                  'Stability_relative_humidity_range',
                  'Stability_temperature_range', 'Substrate_stack_sequence'}


