best_5p_fields = ['Ref_ID', 'Perovskite_band_gap_graded',
                  'JV_certified_values',
       'JV_average_over_n_number_of_cells', 'JV_measured',
       'Ref_part_of_initial_dataset', 'Ref_journal',
       'Ref_original_filename_data_upload', 'Perovskite_dimension_3D',
       'Ref_data_entered_by_author', 'Ref_ID_temp', 'Ref_publication_date',
       'Outdoor_average_over_n_number_of_cells', 'Outdoor_irradiance_measured',
       'Add_lay_back', 'Perovskite_composition_perovskite_inspired_structure',
       'Outdoor_installation_number_of_solar_tracking_axis',
       'Outdoor_periodic_JV_measurements', 'Outdoor_PCE_burn_in_observed',
       'Add_lay_front', 'Perovskite_deposition_number_of_deposition_steps',
       'Perovskite_deposition_solvent_annealing',
       'Perovskite_deposition_quenching_induced_crystallisation',
       'Stability_flexible_cell_number_of_bending_cycles',
       'Perovskite_composition_leadfree', 'Perovskite_composition_inorganic',
       'Perovskite_single_crystal', 'Perovskite_dimension_0D',
       'Perovskite_dimension_2D', 'Perovskite_dimension_2D3D_mixture',
       'Perovskite_dimension_3D_with_2D_capping_layer',
       'Outdoor_detaild_weather_data_available',
       'Outdoor_spectral_data_available', 'Outdoor_tested',
       'Stability_periodic_JV_measurements', 'Stability_light_UV_filter',
       'Stability_average_over_n_number_of_cells', 'Stability_measured',
       'EQE_measured', 'Cell_number_of_cells_per_substrate',
       'Stabilised_performance_measured', 'Stability_PCE_burn_in_observed',
       'JV_light_masked_cell', 'Cell_semitransparent',
       'Cell_semitransparent_wavelength_range', 'Module', 'Cell_flexible',
       'Perovskite_composition_perovskite_ABC3_structure', 'Encapsulation',
       'Module_number_of_cells_in_module',
       'Module_JV_data_recalculated_per_cell',
       'Perovskite_composition_short_form', 'Perovskite_composition_long_form',
       'Ref_lead_author', 'Perovskite_composition_b_ions',
       'Perovskite_composition_c_ions', 'Ref_name_of_person_entering_the_data',
       'Perovskite_composition_a_ions',
       'Perovskite_composition_c_ions_coefficients',
       'Perovskite_composition_b_ions_coefficients', 'JV_light_intensity',
       'Perovskite_composition_a_ions_coefficients', 'HTL_stack_sequence',
       'ETL_stack_sequence', 'Ref_DOI_number', 'Stability_temperature_range',
       'Outdoor_temperature_range', 'Outdoor_location_coordinates',
       'Outdoor_time_start', 'Outdoor_time_end',
       'Stability_light_wavelength_range', 'Stability_relative_humidity_range',
       'JV_light_wavelength_range', 'Outdoor_potential_bias_range',
       'Stability_potential_bias_range', 'Backcontact_stack_sequence',
       'Cell_stack_sequence', 'Substrate_stack_sequence', 'Cell_architecture',
       'Perovskite_dimension_list_of_layers',
       'Perovskite_deposition_aggregation_state_of_reactants',
       'Perovskite_deposition_procedure', 'Backcontact_deposition_procedure',
       'JV_default_PCE_scan_direction', 'JV_default_PCE', 'Cell_area_measured',
       'ETL_deposition_procedure', 'Perovskite_deposition_solvents',
       'JV_reverse_scan_PCE', 'JV_default_Jsc_scan_direction',
       'JV_default_Jsc']